### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

### ISSUE THREAD

**Issue by martin68** [xolox/python-property-manager#1]
These two lines result in the DeprecationWarning
https://github.com/xolox/python-property-manager/blob/5a9e018a3865adefbd48bbda18ed6ba3aaab205d/property_manager/__init__.py#L85
https://github.com/xolox/python-property-manager/blob/5a9e018a3865adefbd48bbda18ed6ba3aaab205d/property_manager/__init__.py#L814

Solution may be https://stackoverflow.com/questions/53978542/how-to-use-collections-abc-from-both-python-3-8-and-python-2-7
Please update the code, thanks!

**Comment by martin68** [comment]
Anyone who'd like to use the package without waiting the issue fixed can see my fork https://github.com/martin68/python-property-manager3
also offered in [pypi ](https://pypi.org/project/property-manager3/)as `property-manager3`

**Comment by xolox** [comment]
I've just merged #2, thanks for your feedback!
